[[destinations]]
type = "log"

[[destinations]]
type = "mqtt"
server = "localhost"
port = 1883
agent_name = "MessageRelayAgent"
publish_channel = "/MetricRelay/"

[[destinations]]
type = "cloudwatch"
namespace = "TestCloudwatchNamespace"
region = "eu-west-2"
profile = "edonica"

[[sources]]
type = "constant"
object = "TestObject"
property = "Temperature"
value = 2.34

[[sources]]
type = "ble"
id = "123"
