[[destinations]]
type = "log"

[[destinations]]
type = "mqtt"
server = "localhost"
port = 1883
agent_name = "MessageRelayAgent"
publish_channel = "/MetricRelay/"

[[destinations]]
type = "cloudwatch"
namespace = "TestCloudwatchNamespace"
region = "eu-west-1"
profile = "edonica"
